# fly.toml app configuration file generated for ash-swarm-empty-field-2922 on 2025-02-26T23:09:08-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ash-swarm-empty-field-2922'
primary_region = 'lax'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'ash-swarm-empty-field-2922.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
