---
    # For configuration options and examples, please see:
    # https://gethomepage.dev/configs/services/
    
    - AI Projects:
        - Twitter Agent:
            href: http://localhost:3005
            description: AI Twitter Client
            icon: si-twitter-#1DA1F2
            ping: true
        - Unbounded:
            href: http://localhost:3001
            description: Generative AI Game Platform
            icon: mdi-brain-#9333ea
            ping: true
            container: unbounded-frontend-1
        - Unbounded API:
            href: http://localhost:8000
            description: Game Backend API
            icon: mdi-api-#6366f1
            ping: true
            container: unbounded-backend-1
        - Unbounded DB:
            href: http://localhost:5432
            description: Game Database
            icon: si-postgresql-#4169e1
            ping: true
            container: unbounded-db-1
        - Ash Swarm:
            href: http://localhost:4000
            description: Adaptive Code Evolution Platform
            icon: mdi-fire-#FF5733
            ping: true
            container: ash_swarm-web-1
        - Ash Livebook:
            href: http://localhost:4001
            description: Interactive Elixir Notebooks
            icon: si-elixir-#4E2A8E
            ping: true
            container: ash_swarm-livebook-1
    
    - pyn8n Services:
        - n8n:
            href: http://localhost:5678
            description: Workflow Automation Tool
            icon: mdi-cog-transfer-#FF6D00
            ping: true
            container: pyn8n-n8n-1
        - Monica CRM:
            href: http://localhost:8081
            description: Personal CRM
            icon: mdi-account-group-#00796B
            ping: true
            container: pyn8n-monica-nginx-1
        - pyn8n API:
            href: http://localhost:8000
            description: Python n8n Client API
            icon: mdi-api-#3F51B5
            ping: true
            container: pyn8n-dev-1
    
    - Infrastructure:
        - Proxmox:
            href: https://192.168.1.123:8006
            description: Virtualization Platform
            icon: si-proxmox-#e57000
            ping: true
            status: https://192.168.1.123:8006
        - Proxmox Scripts:
            href: https://community-scripts.github.io/ProxmoxVE
            description: Community Helper Scripts
            icon: mdi-script-text-#ff5722
            ping: true
        - Coolify:
            href: http://192.168.1.77:8000
            description: Self-Hosted PaaS Platform
            icon: mdi-cloud-sync-#00c4ff
            ping: true
            status: http://192.168.1.77:8000
        - Portainer:
            href: http://192.168.1.135:9000
            description: Docker Management
            icon: si-portainer-#13bef9
            ping: true
            status: http://192.168.1.135:9000
    
    - Media Server:
        - Plex:
            href: http://192.168.1.68:32400/web/index.html
            description: Media Streaming Server
            icon: si-plex-#e5a00d
            ping: true
        - Sonarr:
            href: http://192.168.1.135:8989
            description: TV Shows Management
            icon: si-sonarr-#2596be
            ping: true
        - Radarr:
            href: http://192.168.1.135:7878
            description: Movies Management
            icon: si-radarr-#f7b731
            ping: true
        - Prowlarr:
            href: http://192.168.1.135:9696
            description: Indexer Management
            icon: si-prowlarr-#00c4ff
            ping: true
    
    - Download Clients:
        - qBittorrent:
            href: http://192.168.1.135:8080
            description: Torrent Client
            icon: si-qbittorrent-#2f67ba
            ping: true
        - SABnzbd:
            href: http://192.168.1.135:8085
            description: Usenet Client
            icon: mdi-download-circle-#4caf50
            ping: true
    
    - Network:
        - WireGuard:
            href: http://192.168.1.251:10086
            description: VPN Dashboard
            icon: si-wireguard-#88171a
            ping: true
    
    - Usenet Services:
        - NewsHosting:
            href: https://controlpanel.newshosting.com/customer
            description: Usenet Provider
            icon: mdi-newspaper-variant-#2196f3
            ping: true
        - NZBGeek:
            href: https://nzbgeek.info/dashboard.php?myaccount
            description: Usenet Indexer
            icon: mdi-account-search-#ff9800
            ping: true
        - GeekHub:
            href: https://geek-hub.com.au/member
            description: Private Indexer
            icon: mdi-account-group-#9c27b0
            ping: true
    
    - Ten Framework:
        - Agent Demo:
            href: http://localhost:3200
            description: Ten Agent Demo
            icon: mdi-robot-excited-#00ff00
            ping: true
            container: ten_agent_demo
        - Graph Designer:
            href: http://localhost:3300
            description: Ten Graph Designer
            icon: mdi-graph
            ping: true
            container: ten_graph_designer
        - Agent Playground:
            href: http://localhost:3100
            description: Ten Agent Playground
            icon: mdi-flask-#ff9900
            ping: true
            container: ten_agent_playground
    
    - Database:
        - Qdrant:
            href: http://localhost:6333
            description: Vector Database
            icon: mdi-database-#ff3366
            ping: true
        - PostgreSQL:
            href: http://localhost:5432
            description: PostgreSQL Database
            icon: si-postgresql
            type: postgres
            ping: true
        - Redis:
            href: http://localhost:6379
            description: Redis Cache
            icon: si-redis
            type: redis
            ping: true
    
    - AI Services:
        - Ollama:
            href: http://localhost:11434
            description: Local LLM Server
            icon: mdi-brain-#9933ff
            ping: true
        - Gemini Live:
            href: http://localhost:3004
            description: Gemini Console
            icon: mdi-google
            ping: true
            container: gemini-console
        - Lindy Chat:
            href: https://chat.lindy.ai/home
            description: Lindy AI Chat Interface
            icon: mdi-chat-processing-#33cc33
            ping: true
        - VideoDB Chat:
            href: https://chat.videodb.io
            description: Video Database Chat Interface
            icon: mdi-video-box-#4a90e2
            ping: true
        - Kling AI:
            href: https://klingai.com
            description: AI Development Platform
            icon: mdi-robot-industrial-#00aaff
            ping: true
        - Hailuo AI:
            href: https://hailuoai.video
            description: AI Video Generation Platform
            icon: mdi-movie-edit-#ff6b6b
            ping: true
        - Runway ML:
            href: https://app.runwayml.com/video-tools/teams/batmanosama/dashboard
            description: AI Video Creation & Editing
            icon: mdi-video-wireless-#7b68ee
            ping: true
        - Google AI Studio:
            href: https://aistudio.google.com/tune
            description: LLM Model Tuning Platform
            icon: si-google-#4285f4
            ping: true
    
    - Media:
        - YouTube:
            href: https://www.youtube.com
            description: Video Platform
            icon: si-youtube-#ff0000
            ping: true
    
    - Development:
        - Homepage:
            href: http://localhost:3001
            description: Dashboard
            icon: mdi-view-dashboard-#33ccff
            ping: true
        - Open WebUI:
            href: http://localhost:3000
            description: Web Interface
            icon: mdi-monitor-#00cc99
            ping: true
            container: open-webui
        - MGX Dev:
            href: https://mgx.dev
            description: Development Platform
            icon: mdi-code-braces-#42b883
            ping: true
    